### ISSUE TITLE
The setup.py is not in the docs direcotry

### ISSUE THREAD

**Issue by he1l0world** [coala/coala#5593] opened 2018-07-04 03:29 UTC
When I try to install the coala by the "Development Setup Notes" I found the "setup.py" is not in the docs directory.
"setup.py" is in the coala direcotry.

<img width="715" alt="coala" src="https://user-images.githubusercontent.com/27997963/42255186-63a6a81c-7eff-11e8-99fb-d7b35582271d.png">

**Comment by jayvdb** [comment] 2018-07-05 04:01
This is a duplicate of https://github.com/coala/coala/issues/5449

**Closed by jayvdb** 2018-07-05 04:01 UTC
Labels: area/documentation, difficulty/newcomer, type/bug
