### ISSUE TITLE
Uniform string formatting

### ISSUE THREAD

**Issue by anshalshukla** [coala/coala#6150] opened 2021-03-16 17:33 UTC
Some files in the test module use f string format, whereas others use placeholder syntax. This should be changed and made uniform across all files.

#difficulty/newcomer

**Comment by Shania99** [comment] 2021-03-17 17:38
I am new to open source and would like to take this up.

**Comment by abhishalya** [comment] 2021-03-17 17:40
@Shania99 Sure, go ahead :)

**Comment by codehobbyist06** [comment] 2021-03-20 05:14
Sir, I am a newcomer and would like to work on this issue. Can you pls tell if it is already assigned?

**Comment by Shania99** [comment] 2021-03-20 05:26
@codehobbyist06 Hey! I've been working on this actually.

**Comment by codehobbyist06** [comment] 2021-03-20 05:30
Ok.

**Comment by alphaX86** [comment] 2021-03-22 06:02
Hi @anshalshukla so what kind of formatting you need uniformly in all test module files?

**Comment by alphaX86** [comment] 2021-03-22 06:05
IK the issue is already WIP but I'm asking this to be clear and understandable

**Comment by shobhi1310** [comment] 2021-03-22 08:11
If someone is working on it, it should be marked as assigned to avoid confusion.

**Comment by alphaX86** [comment] 2021-03-22 09:18
Hmm @shobhi1310 I agree

**Comment by anshalshukla** [comment] 2021-03-22 10:38
@alphaX86 I had f-strings on my mind. Since we already use python3.6 using f-strings would be nice in my opinion.

**Comment by alphaX86** [comment] 2021-03-22 11:46
Hmm alright, and could you tell what files I should exactly look on? Coz tests folder is huge and IDK where to exactly look and change on

**Comment by Shania99** [comment] 2021-03-22 11:58
@anshalshukla I am almost done with changing the formatting but I used the old school method of string formatting and not f-strings. Would that be okay?

**Comment by anshalshukla** [comment] 2021-03-22 11:58
You can maybe use grep to search for placeholders and then make the changes. But this issue has already been taken by someone recently so you can look for issues that are unassigned or have been inactive for a while.

**Comment by anshalshukla** [comment] 2021-03-22 12:03
@Shania99 I'm not particularly sure about which one is preferred. But it should be uniform across test module and should have support in future versions of python as well since coala is planning for an upgrade.
@abhishalya can take a stand on what is preferred.

**Comment by abhishalya** [comment] 2021-03-22 12:07
f-strings are the way to go from here on :)

**Comment by Liad-n** [comment] 2021-03-30 13:14
Are there any PRs for this issue yet?

**Comment by echo-outlier** [comment] 2021-04-10 13:00
Can I take this up? I can fix this and make sure that f string format is used in place of placeholder syntax uniformly across all files.

**Comment by Anupam-USP** [comment] 2021-05-01 07:44
Hey! Is this issue still open? Or can I take it?

**Closed** 2021-05-16 15:51 UTC
Labels: difficulty/newcomer, importance/low
