### ISSUE TITLE
Newcomers guide: Add introduction to Gitter 

### ISSUE THREAD

**Issue by NiklasMM** [coala/coala#3958] opened 2017-03-20 15:25 UTC
A Gitter section should be added to the newcomers guide, probably in "Step 1: Meet the community" or as a separate page linked from there.

It should include:

* Short intro (What is Gitter?)
* Explain which channels are there. (Including non-repo related ones like offtopic, conferences....)
* Explain Gitter Etiquette, i.e. don't @-mention or private message people unless they are the only one who could help you. Don't continuously @-mention in an ongoing conversation.

**Comment by adtac** [comment] 2017-03-20 15:28
Maybe also add "do not assign issues through cobot unless you entirely know what the issue is about and how to solve it" (I know it's already in the newcomer invite, but nobody follows it anyway)

**Comment by NiklasMM** [comment] 2017-03-20 15:39
Yes, maybe we could add a short intro to cobot there also!

**Comment by Khushmeet** [comment] 2017-03-30 11:47
I would like to be assigned to this issue.

**Comment by supergr35** [comment] 2017-03-30 19:13
I would really like a short intro to cobot, especially highlighting: issue assignment, marking things wip/pending, and creating issues.

**Closed** 2017-05-25 08:59 UTC
Labels: area/documentation, difficulty/low
