### ISSUE TITLE
coala is not remembering the previous actions in interactive mode

### ISSUE THREAD

**Issue by Abhisek-** [coala/coala#3366] opened 2016-12-22 17:05 UTC
When run coala in interactive mode, it does not remember the changes applied and produces weird ouput.

### Steps to reproduce

1. Create a file, let's say `something.py`, with the following content.

        def fun():
            print('start of the function')

            print('something')  

            print('end of the function')

        if __name__ == '__main__':
            fun()

    **Note**: there are two trailing spaces after `print('something')`
2. After that run `coala -I --bears SpaceConsistencyBear --files something.py -S use_spaces=True`

        something.py:
        |   4| ••••print('something')••
        |    | [NORMAL] SpaceConsistencyBear:
        |    | Line contains following spacing inconsistencies:
        |    | - Trailing whitespaces.
        |----|    | /home/abhisek/Github/coala/something.py
        |    |++++| /home/abhisek/Github/coala/something.py
        |   1|   1| def fun():
        |   2|   2|     print('start of the function')
        |   3|   3| 
        |   4|    |-    print('something')  
        |    |   4|+    print('something')
        |   5|   5| 
        |   6|   6|     print('end of the function')
        |   7|   7| 
        |    | *0: Do nothing
        |    |  1: Open file(s)
        |    |  2: Apply patch
        |    |  3: Print more info
        |    |  4: Add ignore comment
        |    | Enter number (Ctrl-D to exit): 2
        |    | Patch applied successfully.
        |    | *0: Do nothing
        |    |  1: Open file(s)
        |    |  2: Print more info
        |    |  3: Add ignore comment
        |    | Enter number (Ctrl-D to exit): 3
        |    | Please enter a value for the parameter 'language' (No description given.): python
        |    | An ignore comment was added to your source code.
        |    | *0: Do nothing
        |    |  1: Open file(s)
        |    |  2: Apply patch
        |    |  3: Print more info
        |    |  4: Add ignore comment
        |    | Enter number (Ctrl-D to exit): 0

### Observation
1. When entered 2
    It says _it applied the patch_ and then shows 4 options.
    But it should exit at that very moment because after applying
    the patch there is nothing else to do as all the issues has been
    resolved(remember only one line was infected).
2. When entered 3
    It appends a ignore statement to the line to which it just applied a patch in the previous step by
    producing the following.

        def fun():
            print('start of the function')

            print('something')# Ignore SpaceConsistencyBear

            print('end of the function')

        if __name__ == '__main__':
            fun()

    and then again it shows the options!!

**Comment by Makman2** [comment] 2016-12-22 17:10
high importance as this affects usability

**Comment by Mixih** [comment] 2016-12-22 17:25
So after applying the patch, it asks you for input on the same issue? Is this confirmed for all bears, or just that one?

**Comment by RohanVB** [comment] 2016-12-22 17:32
@Mixih looks like that. You could end up with something like this: 
```
 def fun():
     print('start of the function')

     print('something')#IgnoreSpaceConsistencyBear#IgnoreSpaceConsistencyBear# Ignore SpaceConsistencyBear

     print('end of the function')

 if __name__ == '__main__':
     fun()
```

**Comment by Abhisek-** [comment] 2016-12-22 17:39
Yeah, It asks input for the same issue. I think all the bears. But I'm not sure.

**Comment by Mixih** [comment] 2016-12-22 17:45
damn ok this is new

**Comment by Udayan12167** [comment] 2016-12-22 17:56
I'll look into this.

**Comment by Mixih** [comment] 2016-12-22 18:15
Can't confirm in the latest git versions of coala & coala-bears, this issue needs further triaging to locate when it happened, and if/when it was fixed.

**Comment by Makman2** [comment] 2016-12-22 20:44
Behaviour confirmed, but we should part up this issue into 3 parts:
1. After adding an ignore comment, the option should not be available any more.
2. The comment should have one or two spaces after the statement.
3. When applying a patch, don't ask for something else, continue with next result (this would need discussion)

@Abhisek- If you agree we close this issue and I'll open three new ones^^

**Comment by Abhisek-** [comment] 2016-12-23 04:13
yeah go ahead but refer those issues here, so that some one will later get to know what happened with this issue. :)

**Comment by Udayan12167** [comment] 2016-12-23 12:34
[] After adding an ignore comment, the option should not be available any more.
[] The comment should have one or two spaces after the statement.
[] When applying a patch, don't ask for something else, continue with next result (this would need discussion)

**Comment by Makman2** [comment] 2016-12-24 02:40
@Udayan12167 thanks for filing them, wasn't really available past few days

**Comment by Mixih** [comment] 2017-01-03 00:49
should be covered by the three new issues opened by @Udayan12167 .

**Closed by Mixih** 2017-01-03 00:49 UTC
Labels: area/usability, importance/high, type/bug
