### ISSUE TITLE
Error 4 while installing coala-bears

### ISSUE THREAD

**Issue by duskybomb** [coala/coala#5097] opened 2018-01-19 18:50 UTC
I have python version 3.5.2, I wrote the following in terminal
```
$pip3 install coala-bears
```
I got an error:

> Command "python setup.py egg_info" failed with error code 4 in /tmp/pip-build-tyw_Xt/coala/

**Comment by Dragneel7** [comment] 2018-01-21 09:47
@duskybomb I tried the same but was not able to reproduce this error. My python3 version is 3.5.4.

**Comment by duskybomb** [comment] 2018-01-21 18:24
@Dragneel7 use this ``` python3.5 -m pip install coala-bears ```

**Comment by Makman2** [comment] 2018-01-21 21:48
Tested on a fedora docker image with Python 3.5.2, and can't reproduce.

**Comment by Makman2** [comment] 2018-01-21 21:49
@duskybomb Did you have the correct rights during installation?

**Comment by ishanSrt** [comment] 2018-01-23 13:59
@duskybomb I remember the gitter conversation we had. This was all due to your `pip3` using the wrong version of python. Maybe you didn't read my last comment https://gitter.im/coala/coala?at=5a62fe0b9cdc721e4fa57c99
I also gave a solution 😉
@Makman2 you can close this issue as this is not related to coala 👍

**Comment by duskybomb** [comment] 2018-01-23 14:04
@ishanSrt but my pip3 is pointing to the correct directory.

**Comment by ishanSrt** [comment] 2018-01-23 14:06
What does `which pip3` return?

**Comment by ishanSrt** [comment] 2018-01-23 14:10
@duskybomb I don't think that's possible, otherwise the command I gave `python3.5 -m pip install coala-bears` would have never solved it. That ensures that you use the correct `pip` corresponding to the `python3.5.2` you have installed

**Comment by Makman2** [comment] 2018-01-24 15:10
If the command given by @ishanSrt has solved it, the issue can be closed. This indeed looks like an environmental problem not caused by us (esp. because I was able to install coala-bears on a freshly run docker image).

**Closed by Makman2** 2018-01-24 15:10 UTC
Labels: area/install, status/needs info, type/bug
