### ISSUE TITLE
Diff display doesnt show tabs

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#4619] opened 2017-08-05 15:15 UTC
I am 99% sure that tabs were previously visuallised using a unicode arrow, in results with a diff. Now they are gone.

Results without a diff do show the unicode arrow.

**Comment by Nosferatul** [comment] 2017-08-07 08:09
can you give me a screenshot of it with the arrow? I don't think i saw arrows when I used it :)

**Comment by Nosferatul** [comment] 2017-08-07 08:16
The problem is that whatever I deleted from output I added back in https://github.com/coala/coala/pull/4420

**Comment by Nosferatul** [comment] 2017-08-07 08:29
You wanted to say `+` and `-` ?

**Comment by Nosferatul** [comment] 2017-08-11 12:37
I couldn't find the arrows. http://imgur.com/8jHMSpW on the right is `coala` for users and on the left coala for developers. I can't find the arrows in the code either in the output. I'll close this, if you want to open it, please provide an screenshot with the arrows in the output.

**Closed by Nosferatul** 2017-08-11 12:37 UTC
Labels: area/CLI, type/bug
