### ISSUE TITLE
Show file path of bear in --show-details

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#2663] opened 2016-08-23 17:42 UTC
When I do `--show-bears --show-details` I get something like:

```
py35_coala) [ajk@localhost coala]$ coala --show-details --show-bears
[WARNING][23:08:56] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.
[WARNING][23:08:56] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][23:08:56] coala will not run any analysis. Did you forget to give the `--bears` argument?
PEP8Bear
  Detects and fixes PEP8 incompliant code. This bear will not change functionality of the code in any way.

  Supported languages:
   * Python 2
   * Python
   * Python 3

  Used in:
   * default

  No needed settings.

  Optional Settings:
   * max_line_length: Maximum number of characters for a line. (Optional, defaults to '80'.)
   * tab_width: Number of spaces per indent level. (Optional, defaults to '4'.)
   * pep_ignore: A list of errors/warnings to ignore. (Optional, defaults to '()'.)
   * pep_select: A list of errors/warnings to exclusively apply. (Optional, defaults to '()'.)
   * local_pep8_config: Set to true if autopep8 should use a config file as if run normally from this directory. (Optional, defaults to 'False'.)

  Can detect:
   * Formatting

  Can fix:
   * Formatting

```

It would be useful to also show the file where the bear was fetched from.

**Comment by sils1297** [comment] 2016-08-23 18:56
Neat idea.

**Comment by sils1297** [comment] 2016-08-23 18:56
also we don't necessarily print the warning there

**Comment by yash-nisar** [comment] 2016-08-28 04:27
I would like to work on this !

**Comment by yash-nisar** [comment] 2016-09-23 14:32
Could you please provide me subtle hints on this issue @AbdealiJK @sils1297 ?

**Comment by AbdealiJK** [comment] 2016-09-23 15:14
Hi @yash-nisar Check out the variable `args.show_bears` in `coalib/coala.py` which is set to true when the `--show-bears` flag is given. There would be an equivalent `args.show_description`.

Check out what happend when theyre both True and find where the text is being printed. That probably uses a bear class to find this information. Use the `bear.__file__` or similar to find the file where the bear has been taken from and print that too.

**Comment by yash-nisar** [comment] 2016-09-25 12:52
@AbdealiJK The warnings also seem to be unwanted as @sils1297 mentioned above. I have found that these lines are printing the warnings `warn_config_absent(sections, 'files', log_printer),` `warn_config_absent(sections, 'bears', log_printer)` from the load_configuration function. So should I delete those lines ? I think we should keep `The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.` warning. What say ?

**Comment by AbdealiJK** [comment] 2016-09-25 13:59
@yash-nisar I believe he does not want the log messages only in the case of `--show-bears` a `--bears` and `--files` are not needed for `--show-bears`. Hence, we need to add a condition, and not to remove those lines because whern `--show-bear` is being called that's not needed.

I agree that the .coafile warning should still be there, and should be suppressed only when `-I` is used. 

Also, I think supressing the warnings can be made an own issue as that observation was slightly unrelated to the topic of this issue. Feel free to fix it along with this, or create another issue for it.

**Comment by yash-nisar** [comment] 2016-09-25 14:01
Thank you @AbdealiJK . I think I should open another issue regarding the unwanted warnings.

**Comment by yash-nisar** [comment] 2016-09-26 14:34
@AbdealiJK I have a problem. Could you please help me out ?

- I have installed  the latest development snapshot of coala’s master branch from and all of its dependencies with pip using `(venv)$ pip3 install coala-bears --pre`.

- Then I installed a repository-backed version of the repository I was modifying using `(venv)$ pip3 install -e <path/to/clone>`.

- I made some changes in the cloned directory(by creating a new branch on git). The changes include some print statements in the code as breakpoints to check its workflow.

- I am not able to see the changes when I run coala in virtual env.

- Do I have to write additional tests when I write those print statements as break points ?

- I know these questions are very stupid but please try to answer them when you are free. Thanks in advance.

**Comment by mgracer48** [comment] 2016-09-26 16:33
Ill do it

**Comment by yash-nisar** [comment] 2016-09-26 16:57
It would be great if you could help me out. :smile:

**Comment by AbdealiJK** [comment] 2016-09-26 18:53
I did not understand your statement "Do I have to write additional tests when I write those print statements as break points ?".

Why do you say that the changes are not seen when you run coala ? coala suppresses `print` statements in some places. So, if you're saying the change isnt there because youre not seeing some print statement you added - that may not be a correct way of testing if your changes are seen.

Try doing a `raise AssertionError("Yay, the code ran this line!")` instead to check if the code ran upto that point. And run coala with `-v` or `-L DEBUG` to be able to see errors properly.

PS: The `pip install -e` stuff seems correctly done, hence I don't think thats an issue. I'd suggest you get on to https://gitter.im/coala/coala and ask for help for things like this though, figuring it out in an issue is difficult.

**Comment by yash-nisar** [comment] 2016-09-26 19:37
Thank you @AbdealiJK . I appreciate your response. :smile:

**Comment by ashwini0529** [comment] 2016-11-09 18:35
Since the issue is open from so many days, I would like to work upon it.
Could anyone guide me like how to start?
P.S. I'm a newcomer.

**Comment by Nosferatul** [comment] 2016-11-09 18:48
@ashrafmhd09 as you can see someone else is assigned to this issue. Please find something else!

**Comment by Nosferatul** [comment] 2016-11-09 18:48
@yash-nisar still on this?

**Comment by yash-nisar** [comment] 2016-11-09 19:44
Apologies for the delay. I have my end sems going on and will submit a patch as soon as possible.

**Comment by ashwini0529** [comment] 2016-11-09 19:48
Alright! If you need any help, please feel free to ask for! All the best!

**Comment by yash-nisar** [comment] 2016-11-25 14:56
Hey @AbdealiJK ,
I'm planning to add the following snippets in the respective files(excluding the tests). Am I on the right track ?

Filename : ConsoleInteraction.py
```
show_enumeration(console_printer,
                         'File path:',
                         bear.path,
                         '  ',
                         'File path not found.')
```
Filename : Bear.py
```
@classproperty
    def file_path(cls):
        """
        :return: The file where the bear was fetched from.
        """
return cls.__name__
```

**Comment by Mixih** [comment] 2016-11-25 15:03
If I understand what you're doing, you wouldn't have to modify bear.py. You could call self.__file__ on a bear object.

**Comment by Nosferatul** [comment] 2016-12-12 19:45
@yash-nisar are you still on it?

**Comment by yash-nisar** [comment] 2017-01-06 12:29
@Mixih I need some help, are you around ?

**Comment by Mixih** [comment] 2017-01-12 00:54
@yash-nisar Yeah, your original approach is the better way. I forgot magic attributes were class specific. Sorry.

**Comment by yash-nisar** [comment] 2017-01-14 17:48
Is this how we want the path to look @AbdealiJK @sils ?
![screenshot 2017-01-11 21 46 42](https://cloud.githubusercontent.com/assets/14862976/21956859/a194b948-daaf-11e6-89dd-968eff7174d9.png)

**Comment by Makman2** [comment] 2017-01-14 17:59
@yash-nisar sorry for missing your comment...

1. you should indent the text to the other information :)
2. I think you should extend a little bit like this:
```
  Path: ...
or
  Located in ...
```
or similar :)

**Comment by yash-nisar** [comment] 2017-01-14 18:02
Yes, some detailing is remaining. Just wanted to confirm if the path looks similar to what I received as the output. :laughing: Thank you for the feedback @Makman2 . I'm on it.

**Comment by Makman2** [comment] 2017-01-14 18:03
yes looks good :)

**Comment by yash-nisar** [comment] 2017-01-14 18:17
Any further changes required @Makman2 ? Should I initiate a PR ?
![screenshot 2017-01-11 21 46 42](https://cloud.githubusercontent.com/assets/14862976/21957003/bfdac740-dab3-11e6-8fd9-817afa42cb42.png)

**Comment by aptrishu** [comment] 2017-01-14 18:22
Looks good. make the PR @yash-nisar . We'll discuss there if anything further is needed.

**Closed** 2017-01-24 09:25 UTC
Labels: difficulty/low, type/feature
