### ISSUE TITLE
DbusTest is failing when executing twice

### ISSUE THREAD

**Issue by Makman2** [coala/coala#1839] opened 2016-03-07 21:08 UTC
Lately Dbus doesn't like me any more :/
https://gist.github.com/Makman2/eb68dde025995ad270b4

CC @AbdealiJK

**Comment by Makman2** [comment] 2016-03-07 21:08
Happens on Fedora 23, not Windows!

**Comment by sils1297** [comment] 2016-03-07 21:09
I think I got this too

**Comment by AbdealiJK** [comment] 2016-03-08 03:35
@Makman2 - windows should skip dbus test `>_>` (No dbus installed?)

**Comment by Makman2** [comment] 2016-03-08 17:32
On windows it skips^^
and dbus is installed:
```
mak@localhost:~/dev$ sudo dnf install python3-dbus
Last metadata expiration check performed 0:00:01 ago on Tue Mar  8 18:32:07 2016.
Package python3-dbus-1.2.0-12.fc23.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
mak@localhost:~/dev$ python3
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dbus
>>> dbus
<module 'dbus' from '/usr/lib64/python3.4/site-packages/dbus/__init__.py'>
>>> 
```

**Comment by sils1297** [comment] 2016-03-08 17:42
How are you using dnf on windows?

**Comment by Makman2** [comment] 2016-03-08 18:09
Edited my comment :P

**Comment by AbdealiJK** [comment] 2016-03-11 09:01
Interesting. Does this happen repetitively ?

**Comment by AbdealiJK** [comment] 2016-03-11 15:25
So I have no idea how to reproduce this.
Although, what I've done is that Ive added a lot of debugging information in DbusTest which will help in identifying this (or any other erratic dbus behaviour) that comes up.

@Makman2 if this happens frequently can you test and report back with debug information ?

**Comment by Makman2** [comment] 2016-03-11 18:28
This happens everytime running the tests^^ What debug information do you need exactly?

**Comment by AbdealiJK** [comment] 2016-03-11 18:53
Just pull latest master, run pytest and copy paste the output

-----Original Message-----

**Comment by Makman2** [comment] 2016-03-11 19:22
https://gist.github.com/Makman2/d997f3b501bf5a94dbae

**Comment by AbdealiJK** [comment] 2016-03-12 00:56
Hey, so as you see ... It's basically saying "This is a bug" in coala ...
Can you change the log level in DbusDocument::Analyze to debug and try?
We don't have an argparser for this yet :( so there's no cli arg

-----Original Message-----

**Comment by AbdealiJK** [comment] 2016-03-12 03:44
This is being caused by VersionConflict based on the gitter conversation.

https://github.com/coala-analyzer/coala/issues/1748 would have given better debug info
and
https://github.com/coala-analyzer/coala/issues/1800 would solve it.

Closing this

**Comment by AbdealiJK** [comment] 2016-03-12 03:54
Reopening as @Makman2 found another issue :)

**Comment by Makman2** [comment] 2016-03-25 00:56
It's not failing on master (more or less), not sure if it was the issue we talked about, but I see the dbus service remains open after test, the script inside the tests (executed via `python -c ...`) that spawns it up doesn't get closed again, leading to a timeout fail when rerunning tests again.

**Comment by sils1297** [comment] 2016-03-25 09:51
ah that one should be fixed asap

**Comment by hypothesist** [comment] 2016-03-25 10:11
In case someone wants a temporary workaround: run `py.test` with `-k "not Dbus" ` if you don't want to wait for the 35 second timeout.

**Comment by AbdealiJK** [comment] 2016-03-25 10:33
@hypothesist this happens to you too ? I thought this was fedora only.
I cannot seem to reproduce it on Ubuntu. I know it doesnt happen on circleci (Hence, it seems to be working in Ubuntu 12.04 and 14.04)
Which OS do you use ?

The only think I can think of is doing `session_bus.close()` *somehow* in the subprocess ...
We could do that by catching the signal and doing it: http://stackoverflow.com/questions/930519/how-to-run-one-last-function-before-getting-killed-in-python
Also, one other thing would be to check if the tearDown actually happens. (No reason for it not to though.)

**Comment by hypothesist** [comment] 2016-03-25 10:37
@AbdealiJK yeah, I use Fedora 23 too. I assumed it was just happening only to me since I broke some stuff trying to modify the system a week ago.

**Comment by hypothesist** [comment] 2016-04-07 16:29
I have a piece of information that may be useful to the person taking up this: it seems `DbusTest` does **not** fail the first time I run `py.test` after a reboot. But it fails every time after that.

**Comment by Makman2** [comment] 2016-04-07 16:35
@hypothesist yeah because the DBus process is not closing. On the first run it starts up properly and everything connects nicely, but after that it starts to block because it's already open^^

**Comment by Makman2** [comment] 2016-04-07 16:36
you can manually kill the python instance invoked with the code-snippet inside the test (this big chunk of code directly passed to the cmdline), then you can rerun tests even without reboot^^

**Comment by sils1297** [comment] 2016-09-13 13:32
@Makman2 still reproducable?

**Comment by Makman2** [comment] 2016-09-13 16:15
yes, DbusTest fails when executing twice^^

**Comment by sils** [comment] 2016-11-09 16:38
Closing as wontfix as we're going to remove dbus.

**Closed by sils** 2016-11-09 16:38 UTC
Labels: area/tests, importance/low, type/bug
