### ISSUE TITLE
MalformedComment: line -> line number

### ISSUE THREAD

**Issue by SanketDG** [coala/coala#4644] opened 2017-08-17 02:24 UTC
in the docstring of `__init__`

**Comment by aasiya13** [comment] 2017-08-17 08:37
how can i fix this. need more detail..

**Comment by Nosferatul** [comment] 2017-08-17 10:11
MalformedComment is a class in `DocumentationComment.py` file. please check it out and do the necessary changes.

**Comment by aasiya13** [comment] 2017-08-17 10:55
i'm sorry. i'm really new to open source. please help me with what changes to do.

**Comment by SanketDG** [comment] 2017-08-17 16:00
@aasiya13 Assuming you have found the `__init()__` method of `MalformedComment`, you need to change the description of `param line` in the docstring

**Comment by RJ722** [comment] 2017-08-17 16:26
@aasiya13 You need to change the word `line` to `line_number` appearing here: https://github.com/coala/coala/blob/0f8158322cc2bedc14967ea8d3d03bfad908f659/coalib/bearlib/languages/documentation/DocumentationComment.py#L299-L312

If you need any help regarding git, github workflow hop onto the gitter channel. :)

**Comment by aasiya13** [comment] 2017-08-24 07:05
yes

**Comment by sanketnavin** [comment] 2017-09-12 16:20
@aasiya13 are you still working on this issue, since there has been no update since 19 days

**Comment by sanketnavin** [comment] 2017-09-14 18:11
I would like to work on this issue. Can I get assigned to this?

**Comment by aasiya13** [comment] 2017-09-15 17:14
sure. i'm really busy at this moment

**Comment by SanketDG** [comment] 2017-09-16 04:30
@sanketnavin read the [Newcomer's Guide](https://coala.io/newcomer) and you can just assign this to yourself

**Comment by mansiagarwal451** [comment] 2017-10-16 08:02
I am new to open-source. I tried cobot assign but it didn't work. Is there someone working on this? If not, can I get assigned to this issue?

**Comment by SanketDG** [comment] 2017-10-16 16:00
@mansiagarwal451 you used `cobot`, you have to use `corobo`

**Comment by mansiagarwal451** [comment] 2017-10-16 19:43
I tried `corobo assign coala/coala#4644` and got the following message:
`The issue is already assigned to someone. Please check if the assignee is still working on the issue, if not, you should ask for reassignment.`

**Comment by aptrishu** [comment] 2017-10-16 19:47
Yeah it is already assigned to @aasiya13 , can you find another issue ?

**Comment by aptrishu** [comment] 2017-10-16 19:47
Unassigned @aasiya13 due to inactivity.

**Closed** 2017-10-17 18:40 UTC
Labels: difficulty/newcomer
