### ISSUE TITLE
fixture 'mocker' not found error when running py.test

### ISSUE THREAD

**Issue by ma3lstrom** [coala/coala#2839] opened 2016-10-06 14:10 UTC
Running py.test fails as the fixture 'mocker' is not found for the disable_bears fixture at coala/tests/settings/conftest.py. 
![mocker_bug](https://cloud.githubusercontent.com/assets/1377982/19155605/ee45937c-8b93-11e6-90c6-74162b518aa3.png)

labels: difficulty/low, hacktoberfest

**Comment by ma3lstrom** [comment] 2016-10-06 14:10
I suspect that this might be because the mocker python library is not installed

**Comment by virresh** [comment] 2016-10-06 18:56
I'd like to work on this. Please assign this to me.

**Comment by victor-torres** [comment] 2016-10-09 16:49
Cannot reproduce @ OS X.

Maybe lack of `pip install -r test-requirements.txt`?

**Comment by sils** [comment] 2016-10-09 17:41
Yes @ma3lstrom that looks like a typical `pip install -r test-requirements.txt` missing. Closing as invalid, if you have a suggestion on how we can make it more intuitive feel free to open an issue. If this doesn't fix your issue, of course reopen it.

**Closed by sils** 2016-10-09 17:41 UTC
Labels: area/tests, difficulty/low, hacktoberfest, status/invalid
