### ISSUE TITLE
help(coalib) isnt very helpful

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala#1663] opened 2016-02-23 06:06 UTC
Currently `import coalib` followed by `help(coalib)` is not very useful. It just gives a list of packages inside. We should ideally have a description of coala/coalib there too.

I think we need to add a doc-comment  in coalib.__init__.py which gives better information.

We could also use this in the `setup.py` maybe ?

**Comment by AdeshAtole** [comment] 2016-02-23 19:58
Can I do this?

**Comment by sils1297** [comment] 2016-02-23 22:00
@AdeshAtole hey, you've got an invitation to our team. Accept at github.com/coala-analyzer and we can assign you.

**Comment by sils1297** [comment] 2016-02-23 22:00
thanks for your interest :)

**Comment by AdeshAtole** [comment] 2016-02-24 05:06
@sils1297 I have accepted the invite

**Comment by AbdealiJK** [comment] 2016-02-24 06:43
@AdeshAtole I've assigned this to you

**Comment by AdeshAtole** [comment] 2016-02-29 06:41
@AbdealiJK Please unassign me from this issue. I already have a PR merged for a newcomer issue.

**Comment by AbdealiJK** [comment] 2016-02-29 07:06
done

**Comment by Adrianzatreanu** [comment] 2016-08-19 12:06
This issue was moved to coala-analyzer/documentation#54

**Comment by wimpykid26** [comment] 2016-09-17 18:37
Can I work on this?

**Comment by sils1297** [comment] 2016-09-17 18:47
Sure! Let us know if you need anything or if the issue is unclear!

**Comment by wimpykid26** [comment] 2016-09-17 18:51
@sils1297 I am a complete newbie to coala. Where do I find the coalib.init.py file? and what description needs to be shown after running help(coalib)?. Thanks in advance!

**Comment by sils1297** [comment] 2016-09-17 18:54
For the `help` thingie you'll have to google how python does that. The file you want to look at is probably `coalib/__init__.py`

**Comment by wimpykid26** [comment] 2016-09-17 21:38
@sils1297 What does 'description of coala/coalib' mean in the issue statement. A general overview of what the library does?

**Closed** 2016-09-21 18:22 UTC
Labels: area/documentation, difficulty/newcomer
