### ISSUE TITLE
Clear anomaly between “Fixes” & “Closes”

### ISSUE THREAD

**Issue by prnvdixit** [coala/coala#4769] opened 2017-10-21 18:44 UTC
The commit guide doesn't make it clear when to use "Fixes" and "Closes" for documentation changes. The commit guide should be modified to convey that “Fixes” should be used only for those issues that are labelled “bug” - “Closes” works for pretty much everything else.

Label: initiatives/gci

**Comment by Makman2** [comment] 2017-10-22 20:52
Duplicate of https://github.com/coala/documentation/issues/465 :)

**Closed by Makman2** 2017-10-22 20:52 UTC
Labels: area/documentation, initiatives/gci

**Comment by prnvdixit** [comment] 2017-10-23 03:40
@Makman2 I think https://github.com/coala/documentation/issues/465 is related to amending ```Newcomer's Guide``` - I found that distinction between keywords is not clear in ```Commit Guide``` [here](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference) too 😉

**Comment by Makman2** [comment] 2017-12-16 19:15
Probably it's best to put it into commit guidelines only, not to clutter the newcomer's guide even more.
