### ISSUE TITLE
Git_Basics.rst: Correct maximum line length of commit body

### ISSUE THREAD

**Issue by sangamcse** [coala/coala#5777] opened 2018-10-02 10:26 UTC
Right now, it is mentioning 50 characters length for commit body which should be 72.

https://github.com/coala/coala/blob/master/docs/Developers/Git_Basics.rst#adding-the-files-and-commiting

**Comment by bhawesh96** [comment] 2018-10-02 10:44
Please assign this issue to me

**Comment by Ishaan28malik** [comment] 2018-10-03 16:07
can i contribute this ?

**Comment by shivank1234** [comment] 2018-10-03 17:03
Can I help here?

**Comment by bhawesh96** [comment] 2018-10-03 17:45
I have already submitted a PR for this issue.

**Comment by shivank1234** [comment] 2018-10-05 05:17
Ok,NP😊😊
Then,why is the issue is not closed?🤗🤔

**Comment by 7princekumar** [comment] 2018-10-08 05:32
Please assign if not yet solved.

**Comment by jayvdb** [comment] 2018-10-08 05:49
It already has a PR @7princekumar .  I've assigned it to the PR author now.

**Comment by 7princekumar** [comment] 2018-10-08 05:50
> It already has a PR @7princekumar . I've assigned it to the PR author now.

Okay. I will look for another issue to work on. :smile: There are very few newcomer issues left.

**Closed** 2018-10-12 11:57 UTC
Labels: area/documentation, difficulty/newcomer
