### ISSUE TITLE
.coafile: Replace default section with all

### ISSUE THREAD

**Issue by MacBox7** [coala/coala#5307] opened 2018-04-02 19:44 UTC
Refer https://github.com/coala/coala-bears/issues/2397
difficulty/newcomer

**Comment by yzgyyang** [comment] 2018-04-04 23:40
Can I get assigned to this one? It's my first newcomer issue.

**Comment by himanshuc3** [comment] 2018-04-06 13:28
@Makman2 Can I take this one?

**Comment by jayvdb** [comment] 2018-04-06 14:04
I've assigned one newcomer issue to @himanshuc3 , so this one is still up for grabs

**Comment by jayvdb** [comment] 2018-04-06 15:53
See https://github.com/coala/coala-bears/pull/2402 ; which was the same change in a different repo

**Comment by sachinmukherjee** [comment] 2018-04-09 11:35
@jayvdb can I solve this issue?

**Comment by sachinmukherjee** [comment] 2018-04-14 13:47
@MacBox7 created a PR at https://github.com/coala/coala/pull/5384 can you review it?

**Comment by jayvdb** [comment] 2018-04-15 13:02
Oh I see you've created a new PR.
Please dont do that again.

**Comment by sachinmukherjee** [comment] 2018-04-15 13:07
@jayvdb I'm completely messed up with git commands. Sorry

**Comment by ishanSrt** [comment] 2018-05-07 19:58
Duplicate of https://github.com/coala/coala/issues/4127
This needs to be opened in all the repos. Close one of these in this repo.

**Comment by jayvdb** [comment] 2018-05-08 02:48
Duplicate of #4127

**Comment by jayvdb** [comment] 2018-05-08 02:49
Actually we need to migrate .coafile to mobans to be maintainable.

**Closed by jayvdb** 2018-05-08 02:48 UTC
Labels: difficulty/newcomer
