### ISSUE TITLE
Change cobot to corobo in Review.rst

### ISSUE THREAD

**Issue by Pratul1997** [coala/coala#4879] opened 2017-11-17 05:00 UTC
For changing label we do `corobo mark wip <url>` but in documentation it is given `cobot mark wip <url>`

Replace `cobot` with `corobo` in [Review](http://api.coala.io/en/latest/Developers/Review.html).
Relevant file can be found [here](https://github.com/coala/coala/blob/master/docs/Developers/Review.rst)

**Comment by prnvdixit** [comment] 2017-11-17 08:23
@Pratul1997 Close this issue - Duplicate of https://github.com/coala/coala/issues/4840. Please, take a look at existing issues before making new issues (GitHub advanced search comes handy in such cases). :smile:

**Comment by jayvdb** [comment] 2017-11-27 06:34
It is better to have one issue per each file for newcomer issues.

**Comment by kiryteo** [comment] 2017-11-27 11:27
Can I take up this issue?

**Comment by jayvdb** [comment] 2017-12-01 09:12
@yashraj-Dhanuka, only Google Code-in students should take this issue.

**Closed** 2017-12-01 12:54 UTC
Labels: area/documentation, difficulty/newcomer, initiatives/gci
