### ISSUE TITLE
DocumentationAPI Bug with `C` test cases.

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4548] opened 2017-07-24 06:21 UTC
We now use `markers.split()` to find docstrings. Amend the changes to `assemble()`
https://github.com/coala/coala/pull/4530/files#r128902524
Opened by @damngamerz at [gitter//damngamerz](https://gitter.im//damngamerz?at=597591db614889d475e41f4e)

**Comment by damngamerz** [comment] 2017-07-24 06:24
Tried amending the changes to `assemble()` This breaks all other tests. Not able to find a proper solution

**Comment by damngamerz** [comment] 2017-08-03 06:51
we use `marker.split()` to find docstrings...
This would successfully parse Case 1 and 2.
Case 1
```
/**
 * Returns an String that says Hello with the name argument.
 *
 * @param  name the name to which to say hello
 * @return      the concatenated string
 */
```
Case 2
```
/**
* Returns an String that says Hello with the name argument.
*
* @param  name the name to which to say hello
* @return      the concatenated string
*/
```
But when we apply `marker.split()` in `assemble()` (which is a probable solution to this bug). The Case 1 docstring would be assembled to Case 2. Which is the intended behavior but will break whole API.

**Comment by NiklasMM** [comment] 2017-08-07 15:12
```
/**
* Returns an String that says Hello with the name argument.
*
* @param  name the name to which to say hello
* @return      the concatenated string*/
```

**Comment by damngamerz** [comment] 2017-08-07 15:16
markers `['/**',' *',' */']`

**Comment by damngamerz** [comment] 2017-08-10 16:04
we can't fix this by expanding `indent`( with markers), as at some point I have to integrate it into the `assemble()`. Which will break all other test cases as `assemble()` is the only thing which makes sure that the markers are perfect(as markers amending is done in `assemble`). And by expanding the `indent`(with markers), we will be introducing faulty markers into `assemble()`.

Right now what I think DocumentationAPI doesn't care about something which has faulty markers. So best solution atm is to raise error.

**Comment by NiklasMM** [comment] 2017-08-11 06:53
I'm not sure I understand. 

Your idea was to have an additional set that defines the indentation of each marker: `marker_indentation = [1, 2, 1]` for example, right?

If you read them during extraction and apply them again during `assemble` what would go wrong?

**Comment by damngamerz** [comment] 2017-08-11 11:11
Indeed, this was the solution we discussed.
Now what will probably go wrong is....
We assemble markers at the end i.e. in `assemble()`. Which takes care of perfect markers being assembled. Now by applying the solution we will be introducing faulty markers. This will fix the corner case, but the whole picture will get disturbed. And we wont be able to fix those faulty markers(as its been amended at last by `assemble`). 
The thing I meant is that DocumentationAPI will not care about anything if it's markers are faulty. From the extraction till the assembling if something is wrong with the markers itself, documentationAPI will just ignore them and fails.

**Closed** 2017-08-17 14:29 UTC
Labels: area/tests
