### ISSUE TITLE
"Warning: the bear ... failed" should include the filename on which it failed

### ISSUE THREAD

**Issue by sils** [coala/coala#2693] opened 2016-08-31 17:23 UTC
later on the next gen bear design it should include the `str` conversion of the task object.

Otherwise it's like "hell coala failed on everything" when it only failed on a few files.

**Comment by sils1297** [comment] 2016-08-31 17:23
CC @Udayan12167 next gen related

**Comment by Makman2** [comment] 2016-08-31 17:28
the task object should appear in the debug logs imo, not by default^^

**Comment by sils1297** [comment] 2016-08-31 18:23
Its string representation should be short and it should be there by default
definitely because otherwise the warning is rather useless, like our
current exception warning which doesn't give any information and you always
have to get to debug level.

**Comment by Nosferatul** [comment] 2016-09-25 15:51
Can you guide me to the files that need to be changed?

**Comment by Makman2** [comment] 2016-09-25 20:21
@Nosferatul this is related to the next-gen-bears implementation, can't be done yet as we don't use "task" objects currently :)

**Comment by Nosferatul** [comment] 2016-09-25 21:39
Oh, my bad :)

**Comment by Makman2** [comment] 2016-09-25 21:51
oh wait I've misread a bit, you can already try to implement this (forget about the task object, but printing the filename should be possible) :D
@Nosferatul

**Comment by Nosferatul** [comment] 2016-09-25 21:54
Ok, from where should I start?

**Comment by Makman2** [comment] 2016-09-25 22:01
https://github.com/coala/coala/search?utf8=%E2%9C%93&q=failed+to+run

in specific
https://github.com/coala/coala/blob/4e94cdda8dd7793450c97f43c531173bff65bd24/coalib/processes/BearRunning.py
and
https://github.com/coala/coala/blob/7a1f395b162b64e6c4366298dedc17a8563e2dd2/coalib/bears/Bear.py
I think^^

**Comment by Nosferatul** [comment] 2016-09-25 22:23
Ok, I'll check it! Thank you!

**Comment by prafful002** [comment] 2016-10-08 05:42
@sils can I give this assigned to me if noone is working on it ?

**Comment by sils** [comment] 2016-10-08 08:23
@prafful002 there you go

**Comment by nemaniarjun** [comment] 2016-11-24 03:40
Can I work on this? It hasn't been updated in a while.

**Comment by Nosferatul** [comment] 2016-11-24 07:02
@prafful002 any progress?

**Comment by yash-nisar** [comment] 2017-01-19 18:30
Since a majority of the issues have been assigned, can I work on this ? @sils @Makman2

**Comment by yash-nisar** [comment] 2017-01-20 12:44
@sils Can you point me to the steps to reproduce the following warning ? 
`Warning: the bear ... failed`

**Comment by sils** [comment] 2017-01-20 12:58
from `git grep failed`: `coalib/bears/Bear.py:            self.warn('Bear {} failed to run. Take a look at debug messages'`

Reproducing it should be trivial by inserting some raise Exception in a bear and running that

**Comment by yash-nisar** [comment] 2017-01-23 04:46
* Should I include the absolute path of the file or only the filename ?
ie. `/home/..../filename.py` or `filename.py` ? 
* I'm planning to add `self.warn('Bear {} failed to run on {}. Take a look at debug messages'
' (`-V`) for further information.'.format(name, args[0]))` with the suitable tests. Is that what we want @sils @Makman2 ?

**Comment by Makman2** [comment] 2017-01-23 10:01
- absolute path
- what is `args[0]`?

**Comment by yash-nisar** [comment] 2017-01-23 12:47
* args[0] used to give me the filename including the absolute path. However it is giving me an empty tuple now. args[1] used to contain the entire content of the file.

**Comment by Makman2** [comment] 2017-01-23 12:55
ah in `Bear.run_from_section`... Though the message does only work for local bears, for global bears you can't say which file produced an error^^

**Comment by yash-nisar** [comment] 2017-02-03 18:39
How should we tackle this for global bears ? @Makman2

**Comment by meetmangukiya** [comment] 2017-02-04 10:27
A ugly solution could be..
1. Implement handle_error in GlobalBear.py which takes the filename arg
2. Trust the developer to make a call on that, but I think we don't need this for GlobalBears :thinking:

**Comment by yash-nisar** [comment] 2017-02-04 11:06
IIUC, the message will only be displayed for local bears ? CC @meetmangukiya @Makman2 
Should I initiate a PR ?

**Comment by Makman2** [comment] 2017-02-04 13:44
yeah only display for local bears^^

**Comment by yash-nisar** [comment] 2017-02-04 13:47
Awesome !

**Closed** 2017-02-13 20:17 UTC
Labels: area/CLI, area/usability, difficulty/low, hacktoberfest
