### ISSUE TITLE
Bears - Required files not installed

### ISSUE THREAD

**Issue by jschwarzwalder** [coala/coala#2360] opened 2016-06-18 10:34 UTC
I wanted to run coala on some html files.

I went to [coala-analyzer.org](http://coala-analyzer.org/) and saw the sections under Try it

`cd project && coala --files="**/*.py" --bears=PEP8Bear --save`

I had moved to the directory that held my html flies so i typed in `coala --files=*.html" --bears=BootLintBear --save`

I'd gotten BootLintBear from the list of [supported Languages](https://github.com/coala-analyzer/bear-docs/blob/master/README.rst). There were only two listed under HTML, so I selected BootLint since I'd used boostrap in my project.

I got an error that bootlint is not installed. 

When I look at the [description of BootlintBear ](https://github.com/coala-analyzer/bear-docs/blob/master/docs/BootLintBear.rst) is says I can learn more about about bootlint at https://github.com/twbs/bootlint#bootlint but doesn't mention that I need to install bootlint for it to work.

Is there some step I missed to get it to run properly?

![image](https://cloud.githubusercontent.com/assets/8946787/16170353/b6fd29ec-3504-11e6-85f3-3117249ef3ca.png)

**Comment by AbdealiJK** [comment] 2016-06-18 10:36
This is kind of a duplicate of https://github.com/coala-analyzer/coala-bears/issues/432 I think

Also, currently we don't install a bear's dependency if the dependency is non-pythonic. But it's in the works - @Adrianzatreanu is working on it.

@Adrianzatreanu is there a tracking issue for the bear dependency management and splitting bears ? I can't seem to be able to find it.

**Comment by jschwarzwalder** [comment] 2016-06-18 10:48
Sorry I'd only looked on coala to see if it had been reported.

I think I would have liked to know that I'd have to download and install boot linter . I"m guessing at this point i get it from the linked github page...

**Comment by sils1297** [comment] 2016-06-18 11:09
yes the messages should be better

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Makman2** [comment] 2016-06-18 12:44
hm, when the message says bootlint is not installed, then I would assume I need to install bootlint :)
I don't think we need to change messages, @jschwarzwalder your "documentation-workflow" was completely right, you've looked at bootlint, even at the bear description which refers to the github page with documentation, and there it is: https://github.com/twbs/bootlint#on-the-command-line
a little one liner for installing bootlint (assuming `npm` is installed which is part of node) :+1:

**Comment by sils1297** [comment] 2016-06-18 12:59
I think we should provide install instructions or at least a URL or so?

**Comment by Makman2** [comment] 2016-06-18 18:52
an URL doesn't harm I think :)

**Comment by sils** [comment] 2016-12-11 10:43
closing this in favour of https://github.com/coala/coala/issues/3219 which will solve this.

**Closed by sils** 2016-12-11 10:43 UTC
