### ISSUE TITLE
Fix broken links in Development_Setup.rst

### ISSUE THREAD

**Issue by stobis** [coala/coala#5556] opened 2018-06-22 18:56 UTC
There are two broken links in  [Development Setup Notes](https://api.coala.io/en/latest/Developers/Development_Setup.html):

1. In _venv_ section:
> Now you can activate the environment and start [the next part](https://api.coala.io/en/latest/Developers/Development_Setup.html#id1).

Which should probably point to _Repositories_ section(?)

2. In _Using virtualenv_ section:
> After this, you can start [installing from git](https://api.coala.io/en/latest/Developers/Development_Setup.html#id1).

Which should point to _Installing from Git_ 

It looks like issue for newcomers.

**Comment by starkblaze01** [comment] 2018-06-22 22:36
Please assign this issue to me.

**Comment by starkblaze01** [comment] 2018-06-22 22:51
Please assign this issue to me.

**Comment by 0110G** [comment] 2018-06-24 05:08
Is this issue still pending ?

**Comment by hvp004** [comment] 2018-06-26 14:38
If the issue is still up for grab, can I be assigned to the issue?

**Closed** 2018-06-28 12:52 UTC
Labels: area/documentation, difficulty/newcomer, type/bug
