### ISSUE TITLE
Add note discouraging CircleCI on forks

### ISSUE THREAD

**Issue by co-robo** [coala/coala#4820] opened 2017-11-01 09:58 UTC
http://api.coala.io/en/latest/Developers/Adding_CI.html 
Circle CI should only be enabled on forks to debug problems with Circle CI.
difficulty/newcomer
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=59f99ace81cd9a5d7e9ffe76)

**Comment by supriyanta** [comment] 2017-11-01 15:56
please guide me how to fix it?

**Comment by acashmkj** [comment] 2017-11-01 20:47
@jayvdb the note is already there. Do you want to enhance it ?

Note

Please refrain from enabling CircleCI on your fork since they use shared build pools. You can use TravisCI instead if you need access to private builds.

**Comment by supriyanta** [comment] 2017-11-02 05:47
Yes!

**Comment by d3vil0p3r** [comment] 2017-11-03 07:17
@supriyanta are you still working on this?

**Comment by rattandeep1998** [comment] 2017-12-15 10:19
Hey,

Can I work on this issue ?

**Comment by RaiVaibhav** [comment] 2017-12-15 10:28
@supriyanta , ping 
please assign yourself only to one `newcomer` issue, if you are facing in understanding of `issue`, contact for help on `gitter`.
There is already a open PR of yours on newcomer issue https://github.com/coala/coala-bears/pull/2123

**Comment by Makman2** [comment] 2017-12-15 17:44
Unassigned due to inactivity.

**Comment by shashank-b** [comment] 2017-12-19 04:02
Please assign this issue to me.

**Comment by jayvdb** [comment] 2017-12-20 05:53
Duplicate of https://github.com/coala/coala/issues/4006

**Closed by jayvdb** 2017-12-20 05:53 UTC
Labels: difficulty/newcomer
