### ISSUE TITLE
Linter.py: Change docstring

### ISSUE THREAD

**Issue by srisankethu** [coala/coala#2986] opened 2016-11-11 09:01 UTC
The [docstring](https://github.com/coala/coala/blob/e722d298b4c64d2d9be7b9f03d08a9b70a11e32c/coalib/bearlib/abstractions/Linter.py#L704) describes about RESULT_SEVERITY.MIINOR. Change it to RESULT_SEVERITY.INFO as RESULT_SEVERITY.MINOR does not exist.

area/documentation difficulty/newcomer

**Comment by Makman2** [comment] 2016-11-11 09:09
Duplicate of https://github.com/coala/coala/issues/2816 :)

**Closed by Makman2** 2016-11-11 09:09 UTC
Labels: area/documentation, difficulty/low, difficulty/newcomer

**Comment by srisankethu** [comment] 2016-11-11 09:11
@Makman2 Oops! :+1:
