### ISSUE TITLE
Ignore comment does not work for VultureBear

### ISSUE THREAD

**Issue by Abhisek-** [coala/coala#3365] opened 2016-12-22 14:00 UTC
`VultureBear` is not ignoring the ignore comments that are given for an unused variable or function.

### Steps to reproduce

1. Ceate a file, let's say `something.py`, with the following code

        def fun():  # Ignore VultureBear
            pass

2. Run the following command

        coala -I --bears VultureBear --files something.py -S use_spaces=True

### Actual Result

    Executing section Default...

    something.py
    |   1| def•fun():••#•Ignore•VultureBear
    |    | [NORMAL] VultureBear:
    |    | Unused function 'fun'
    |    | *0: Do nothing
    |    |  1: Open file(s)
    |    |  2: Add ignore comment
    |    | Enter number (Ctrl-D to exit): 0

### Expected Result

    Executing section Default...

**Comment by Makman2** [comment] 2016-12-22 16:03
Does coala ignore the result when your file looks like this?
```
# Ignore VultureBear
def fun():
     pass
```

**Comment by Abhisek-** [comment] 2016-12-22 16:11
Oh it does.
But when my file look like the following

    def fun():
         pass

and when I say _2: Add ignore comment_ then it produces the following

    def fun():  # Ignore VultureBear
         pass

**Comment by Abhisek-** [comment] 2016-12-22 16:14
And yes for `SpaceConsistencyBear`(not sure about other Bears) if my file looks like this

    def fun():
         x = 2  # Ignore SpaceConsistencyBear

then it just ignores and it works fine

**Comment by Makman2** [comment] 2016-12-22 16:38
why `SpaceConsistencyBear` ? :O

anyway, looks like a bug^^

**Comment by Makman2** [comment] 2016-12-22 16:39
importance/high as we suggest an invalid ignore statement which has no effect^^

**Comment by RohanVB** [comment] 2016-12-22 17:25
```
$ python -c "import bears; print(bears.__version__)"
0.10.0.dev20161217220544

$ coala --version
0.10.0.dev99999999999999
```
(dev version after PR: #2883) :Unable to reproduce

File: (zmtest.py)
```
 def fun():  # Ignore VultureBear
     pass
```

Output:
```
$  coala -I --bears VultureBear --files zmtest.py -S use_spaces=True
Executing section Default...

```

Tried it on coala-bears and coala-bears --pre; result was reproducible. 

Conclusion: Issue may have been resolved by #2883 .

**Comment by Makman2** [comment] 2016-12-22 20:22
I'm able to reproduce, coala version is `0.10.0.dev20161222155306`, coala-bears version `0.10.0.dev20161222154541`

**Comment by Makman2** [comment] 2016-12-22 20:32
Unable to bisect, already 500 commits behind current master HEAD, but it seems that this ignore has never worked^^

**Comment by Makman2** [comment] 2016-12-22 20:32
@RohanVB you sure you've execute everything correctly?

**Comment by RohanVB** [comment] 2016-12-24 03:50
@Makman2 well on coala-bears version: 0.10.0.dev20161217220544 and coala version: 0.10.0.dev20161222155306, I'm able to reproduce the issue. For some reason, in the coala-dev version ,0.10.0.dev99999999999999 I'm getting the output as shown in the comment above. The last commit made in that by me was #2883, but whatever the reason be for this, I guess since it isn't in the coala --pre install, we don't need to triage further as to why its occuring, but mark it as a bug.

**Comment by sils** [comment] 2016-12-29 17:34
Likely related to https://github.com/coala/coala/issues/3094

**Comment by jayvdb** [comment] 2018-05-05 23:09
@RJ722 , could you re-test this and investigate fixing it if it is still a problem.

**Comment by RJ722** [comment] 2018-05-07 09:09
I cannot reproduce this on the latest coala release.

**Comment by jayvdb** [comment] 2018-05-07 11:47
Latest published release , or latest `master` ?

**Comment by RJ722** [comment] 2018-05-07 12:02
Latest published release.

**Comment by Makman2** [comment] 2018-05-10 11:15
Please test on latest master, 0.11 is quite old.

**Comment by RJ722** [comment] 2018-05-11 07:19
I checked on latest master:
```
python -c "import bears; print(bears.__version__)"
0.12.0.dev99999999999999
```
It ignores successfully.

**Closed** 2018-05-11 10:30 UTC
Labels: importance/medium, type/bug
