### ISSUE TITLE
Running Coala first time

### ISSUE THREAD

**Issue by shivam207** [coala/coala#3818] opened 2017-03-01 13:26 UTC
After succesfully installing coala, I am running it on the coala-tutorial directory. But, I am getting this error. I tried to run on other codes but got the same error.

Error:
pkg_resources.ContextualVersionConflict: (requests 2.2.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests~=2.12'), {'coala'})

**Comment by Makman2** [comment] 2017-03-01 16:55
As you can see one of the package requirements is not satisfied. Install `requests` version 2.12 :+1:

coala has currently some dependencies which likely crash with existing packages (as `requests`). If you want to separate environments, read http://docs.coala.io/en/latest/Users/Install.html#installing-inside-a-virtualenv :)

Closing as this is not a bug :)

**Closed by Makman2** 2017-03-01 16:55 UTC
