### ISSUE TITLE
Move testfixtures requirement to test-requirements.txt

### ISSUE THREAD

**Issue by Makman2** [coala/coala#5335] opened 2018-04-07 14:16 UTC

**Comment by jayvdb** [comment] 2018-04-07 14:31
I was wondering about this.
It was introduced in b502ad61c.

But the problem is
```
$ git grep testfixtures coalib
coalib/misc/DeprecationUtilities.py:    >>> from testfixtures import LogCapture
```

**Comment by jayvdb** [comment] 2018-04-07 14:32
@shreyans800755 might have some ideas on how we might be able to fix this.

**Comment by Makman2** [comment] 2018-04-07 15:49
Ahhh... sorry I missed that one.

However this is fixable by moving the test to an actual test file. This is not very elegant, but the easiest.

**Comment by jayvdb** [comment] 2018-04-11 23:02
cripes; `textfixtures` is also a dependency of coala_utils
see https://gitlab.com/coala/coala-utils/commit/04a470cceba30dedafdc19539424df9a5e73ca14

**Comment by Makman2** [comment] 2018-04-12 09:11
Ugh okay that's uncool... Maybe we create a coala-testing repo or coala-testing-utils?

**Comment by jayvdb** [comment] 2018-04-12 09:25
a new repo sounds good, but the fundamental problem is that coalib has test helpers in it, so all that needs to be moved out also.

**Comment by alphadose** [comment] 2018-04-12 17:47
@jayvdb how about we add the source code of logcapture itself to the coala_utils repo https://github.com/Simplistix/testfixtures/blob/master/testfixtures/logcapture.py ? That would remove the dependency on testfixtures in the production build. Not very elegant but the easiest one.

**Comment by jayvdb** [comment] 2018-04-13 14:06
No. Then we have to maintain it, and we still have to worry about [its deps](https://github.com/Simplistix/testfixtures/blob/master/setup.py#L36).

**Comment by jayvdb** [comment] 2018-04-16 00:06
Note that this is occurred before the 0.12 branch.
https://github.com/coala/coala/blob/release/0.12/requirements.txt#L12

And happened only in the coala_utils 0.7.0, which is not installed by the currently released 0.11.0.

**Comment by jayvdb** [comment] 2018-04-16 00:14
The use of `textfixtures` via `coala_utils` is only exposed via a `check_logs`, and so far it is only used in the tests, so no 'core' functionality will be broken if it is removed from `coala_utils`.

```py
tests/output/ConsoleInteractionTest.py:from coala_utils.decorators import check_logs
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*deprecation_messages)
tests/output/ConsoleInteractionTest.py:    @check_logs(*(deprecation_messages*5))
```

**Comment by jayvdb** [comment] 2018-04-16 00:37
coala_utils dependency added in https://gitlab.com/coala/coala-utils/merge_requests/52

There does not appear to have been an issue for it.

**Comment by jayvdb** [comment] 2018-04-16 00:39
d56cc7e64 shows that this also caused our dependency on `setuptools` to be bumped higher, so we might be able to revert that also after we've fixed this.

**Comment by jayvdb** [comment] 2018-04-16 06:26
I have one approach to solve part of the problem.
It depends on https://github.com/chadrosenquist/logging-test-case/pull/1 and https://github.com/chadrosenquist/logging-test-case/pull/3 , then we can use that tool to do the log capturing.
https://github.com/jayvdb/coala/commit/b52983aefaebdaa8ed99aabc91802d8a8d36d1bd

There is an unrelated error in the build, due to using my own fork of that package.
https://travis-ci.org/jayvdb/coala/builds/367002980
If the PRs are merged and a new version released, that should be green.

That only removes on of the explicit dependencies.
The other is `check_deprecation` docstring using testfixtures directly.
That is easily solved as the doctest can be simply removed: https://github.com/jayvdb/coala/commit/f0e84c1c74bbb34e661d5f0f40492ddd41f2c29d ; test coverage still passes. (phew)  I suspect that this isnt even necessary.  doctest relying on test requirements is probably ok.

**Comment by jayvdb** [comment] 2018-04-16 08:24
Easiest path forward:

1. https://github.com/coala/coala/pull/5393
2. https://gitlab.com/coala/coala-utils/issues/47 - Revert from coala_utils and release 0.8.0
3. bump coala_utils dependency here
4. jayvdb/coala@f0e84c1 or similar
5. move `testfixtures` to `test-requirements.txt`

**Closed** 2018-07-16 12:54 UTC
Labels: difficulty/low, importance/critical
