### ISSUE TITLE
Mac OS Terminal syntax highlighting colors messed up

### ISSUE THREAD

**Issue by chauffer** [coala/coala#2677] opened 2016-08-28 16:08 UTC
### Overview Description
# Steps to Reproduce
1. Open Terminal.app
2. Run coala using a bear that does syntax highlighting
# Actual Results

![](https://c.meo.ws/ZeroBin__Python__coala__8024_08281806_34fgh.png)
# Expected Results

More readable colors
# Reproducibility

100% on default settings / Mac OS 10.11.6

**Comment by Makman2** [comment] 2016-08-28 16:13
Thanks for submitting this bugreport! Could you append the `index.php` and your `.coafile`? Then it's easier for us to track down the bug as we don't need to construct the issue ourselves :)

CC @Udayan12167 as I don't have a Mac and can't test this :)

**Comment by Makman2** [comment] 2016-08-28 17:01
oh and CC @Adrianzatreanu as he has one too :)

**Comment by Adrianzatreanu** [comment] 2016-08-28 17:13
i confirm, syntax highlighting is unreadable on my mac too. mine is dark colored and the lightly green colors are totally unreadable, i have to copy paste the text sometimes, but i dont encounter it often.

**Comment by sils1297** [comment] 2016-08-28 17:15
CC @mr-karan btw. who did the syntax highlighting

**Comment by mr-karan** [comment] 2016-08-28 18:23
I'm looking at it.

**Comment by sils** [comment] 2016-11-07 16:21
@chauffer @Adrianzatreanu I think https://github.com/coala/coala/issues/2940 would be an immediate fix, on the long run I'm not sure how we can work around ill defined colour schemes. Everything is totally readable on my linux machine whatever colour scheme I chose. (Tried 10 or so, they're all good.) Windows users have the same issue.

**Comment by sils** [comment] 2017-02-05 20:57
duplicate of https://github.com/coala/coala/issues/3544

**Closed by sils** 2017-02-05 20:57 UTC
Labels: area/usability

**Comment by meetmangukiya** [comment] 2017-02-06 07:49
Does it not work even on changing color scheme ? @adrianzatreanu. It should probably work,  but I don't think user will change color scheme for just coala
