### ISSUE TITLE
Undesirable output when Vulture Bear is used

### ISSUE THREAD

**Issue by Naveenaidu** [coala/coala#5242] opened 2018-03-07 17:09 UTC
When i use `VultureBear` along with any other bear the output we get is as:-
```
test.py
[   3] def·test(a1,b1="",c1="",a2):·
**** PEP8Bear [Section: cli | Severity: NORMAL] ****
!    ! The code does not comply to PEP8.
[----] /home/theprophet/test-coala/test.py
[++++] /home/theprophet/test-coala/test.py
[   3] def test(a1,b1="",c1="",a2): 
[   3] def test(a1, b1="", c1="", a2):
[    ] *0. Do (N)othing
[    ]  1. (O)pen file
[    ]  2. (A)pply patch
[    ]  3. Add (I)gnore comment
[    ]  4. Show Applied (P)atches
[    ]  5. (G)enerate patches
[    ] Enter number (Ctrl-D to exit): test.py:11: expected an indented block at "'''
    print(d)

    print(b)
    print(c)
'''"
2
[    ] Patch applied successfully.
[    ] *0. Do (N)othing
[    ]  1. (O)pen file
[    ]  2. Add (I)gnore comment
[    ] Enter number (Ctrl-D to exit): 0
```

The output of the `Vulture Bear` is getting merged into other bears. And also the output of the Vulture Bear gets shown without any interaction of the user.

IMO we should provide a option to the user ,which gives him the freedom to view the result from Vulture Bear whenever he wants.
The desired output IMHO should be:-
```
test.py
[   3] def·test(a1,b1="",c1="",a2):·
**** PEP8Bear [Section: cli | Severity: NORMAL] ****
!    ! The code does not comply to PEP8.
[----] /home/theprophet/test-coala/test.py
[++++] /home/theprophet/test-coala/test.py
[   3] def test(a1,b1="",c1="",a2): 
[   3] def test(a1, b1="", c1="", a2):
[    ] *0. Do (N)othing
[    ]  1. (O)pen file
[    ]  2. (A)pply patch
[    ]  3. Add (I)gnore comment
[    ]  4. Show Applied (P)atches
[    ]  5. (G)enerate patches
[    ]  6. Show VultureBear Output
[    ] Enter number (Ctrl-D to exit):

```
status/needs Discussion
cc @Makman2

**Comment by Naveenaidu** [comment] 2018-03-07 17:20
But the problem here is, How are we going to pass a custom action to output. This is somewhat like https://github.com/coala/coala/issues/3650 .

Or else is there any way in which we can add a action into the action list only for the Vulture Bear. Is it feasible to add specific action like `Show VultureBear Output` to the `cli_actions` present in the `ConsoleInteraction.py` and keep it in the `action list` until the program terminates. Just like `Do (N)othing` is always in the list.

@Makman2 need your opinion on this. And if this is a valid issue, PLease assign me this. :smile:

**Comment by Makman2** [comment] 2018-03-11 15:53
> IMO we should provide a option to the user ,which gives him the freedom to view the result from Vulture Bear whenever he wants.

I don't understand what this has to do with actions. It seems that the output is intermixed with output from other bears, actions won't solve that problem. As far as I understand this is a duplicate of https://github.com/coala/coala/issues/462 .

**Comment by Naveenaidu** [comment] 2018-03-11 16:30
@Makman2 VultureBear prints of the output without even asked for. I mean if we pass two bears say `VultureBear` and `SpaceConsistencyBear` and execute coala then `VultureBear` automatically prints out the output without asking for a input from the user. IMHO I think the user needs to be given an option to view the output from `VultureBear` whenever he wishes to.
But if this is a desired output of the `vulture bear` please be kind enough to mark the issue as `invalid` .

**Comment by Makman2** [comment] 2018-03-11 16:36
I mean if you specify multiple bears, you will be prompted results one by one.

**Comment by Naveenaidu** [comment] 2018-03-11 16:37
But don't you think the user needs to be given an option to view the result from the vulture bear whenever he wishes to?.

**Comment by Makman2** [comment] 2018-03-11 16:39
I mean the result is just an overview, having something like
```
Do you want to see the next result or skip it (from: VultureBear)? [y/n]
```
is counter-productive and annoying for the user imo^^

**Comment by Naveenaidu** [comment] 2018-03-11 16:41
So do you think, it's a invalid issue?

**Comment by Makman2** [comment] 2018-03-11 16:44
Yes :)

**Closed by Makman2** 2018-03-11 16:44 UTC
Labels: area/actions, status/needs info, type/bug
