### ISSUE TITLE
pipenv install coala-bears produces errors

### ISSUE THREAD

**Issue by siddhant-curious** [coala/coala#5796] opened 2018-10-08 12:58 UTC
**Overview Description**
Can not install coala-bears inside a pipenv. 

**Steps to Reproduce**

1. pipenv --Python 3.7 
2. pipenv install coala-bears

**_Output :_** 
`Installing coala-bears...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/core.py", line 1971, in do_install
    pypi_mirror=pypi_mirror,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
`

**Expected Results**

Coala should get installed successfully. 

**Additional Information:**

I am running MacOS Mojave, 10.14 
Installs fine under virtualenv

**Comment by jayvdb** [comment] 2018-10-08 13:21
Duplicate of https://github.com/coala/coala/issues/3677

**Closed by jayvdb** 2018-10-08 13:21 UTC
