### ISSUE TITLE
LocalBearTestHelper: Change the docstring indentation

### ISSUE THREAD

**Issue by newbazz** [coala/coala#5137] opened 2018-02-07 20:38 UTC
difficulty/newcomer

**Comment by flaredragon** [comment] 2018-02-08 05:12
Can I take up this issue?
Could someone please assign me this

**Comment by newbazz** [comment] 2018-02-08 05:13
@flaredragon yes you can, start working on this issue and you will be assigned asap.

**Comment by flaredragon** [comment] 2018-02-08 05:31
@newbazz Sir,I was unable to find any docstrings in LocalBearTest.py in tests/bears folder could you guide me where exactly the changes have to be done?

**Comment by newbazz** [comment] 2018-02-08 05:33
ohh my bad.

**Comment by newbazz** [comment] 2018-02-08 05:34
now check

**Comment by flaredragon** [comment] 2018-02-08 05:36
sir even that file doesn't have any docstrings

**Comment by newbazz** [comment] 2018-02-08 05:39
https://github.com/coala/coala/blob/master/coalib/testing/LocalBearTestHelper.py
it does check carefully. ;)

**Comment by nvzard** [comment] 2018-02-13 19:37
I think its a duplicate of https://github.com/coala/coala/issues/5131

**Comment by Makman2** [comment] 2018-02-14 18:37
Indeed. @flaredragon Sorry I have to close this one. I hope you don't mind.

**Closed by Makman2** 2018-02-14 18:37 UTC
Labels: area/documentation, difficulty/newcomer
