### ISSUE TITLE
Console shows code line corrupted

### ISSUE THREAD

**Issue by simplicbe** [coala/coala#2929] opened 2016-10-30 14:49 UTC
When using the `KeywordBear` and passing `#warning` to it using the _.coala_ file like this:

``` ini
[Default]
language = C\#
bears = SpaceConsistencyBear,KeywordBear,FileNameBear#,CPDBear
files = src/**.cs
use_spaces = yeah
file_naming_convention = pascal
ci_keywords = \#warning
cs_keywords = \#warning
```

The output is corrupted:

![warningbearer](https://cloud.githubusercontent.com/assets/14359329/19837330/39c93092-9eb8-11e6-871b-b02101ea78c0.PNG)

Here is a part of the `c#` source code

``` c#
        /// <summary>
        /// Execute a prepared statement
        /// </summary>
        /// <param name="handle">Handle containing the statement to execute</param>
        /// <param name="errorListener">Error listner that will be used</param>
        /// <returns>Null if the query is invalid, else an sql result</returns>
        public OdbcResult ExecuteStatement(OdbcExecute handle, SqlErrorListener errorListener)
        {
            // Get query from cache
            var cacheObj = OdbcCache.GetQuery(handle.Handle);

            // Create a new sql context so we can execute a compiled query, even if we are in another
            // cdn node (not yet but maybe later)
#warning We should implement it for cross node compatibility
            var executor = new SqlExecutor();
            var sql = new Sql(executor, errorListener);

            var parameters = new List<QueryParameter>();

            if (handle.Parameters != null)
            {
                if (handle.Parameters != null)
                {
                    foreach (var p in handle.Parameters)
                    {
                        var parameter = new QueryParameter()
                        {
                            Name = p.Name,
                            Value = p.Value
                        };
                        parameters.Add(parameter);
                    }
                }
            }

            // Excecute compiled query
            var result = sql.Execute(cacheObj.Query, parameters);
            var rows = new List<IList<object>>();

            // Create error result
            if (errorListener.ErrorList.Count == 0)
            {
                // Define meta result
                var meta = new OdbcResultMeta();

                //  __amount__ exists if we have an insert
                if (result.Definition.Count == 1 && result.Definition.ContainsKey("__amount__"))
                {
                    meta.Columns = new List<OdbcResultColumn>();
                    meta.AffectedRows = (int)result.Rows[0].Columns["__amount__"];
                }
                else
                {
                    meta.RowCount = result.Rows.Count;
                    meta.Columns = new List<OdbcResultColumn>();

                    // Add queried columns
                    foreach (var column in result.Definition)
                    {
                        if (column.Key?.ToLower() == "archiv_guid")
                        {
                            var col1 = new OdbcResultColumn() { Name = "archiv_guid", Type = -11, Nullable = true, Size = 0 };
                            meta.Columns.Add(col1);
                        }
                        else if (column.Key?.ToLower() == "archiv_blob")
                        {
                            var col1 = new OdbcResultColumn() { Name = "archiv_blob", Type = -4, Nullable = true, Size = 0 };
                            meta.Columns.Add(col1);
                        }
                    }

                    foreach (var res in result.Rows)
                    {
                        var lst = new List<object>();

                        foreach (var col in res.Columns)
                        {
                            lst.Add(col.Value);
                        }

                        rows.Add(lst);
                    }
                }

                return new OdbcResult()
                {
                    Meta = meta,
                    Rows = rows
                };
            }

            return null;
        }
```

Using **coala 0.8.1**

**Comment by AbdealiJK** [comment] 2016-10-31 02:58
Could you copy paste those characters that are being printed instead of spaces ? (Rather than a screenshot)
I am unable to type it and would like to copy it to see the hex version and play around with it in `print()` and stuff.

**Comment by Makman2** [comment] 2016-10-31 15:11
Duplicate of https://github.com/coala/coala/issues/2753 :)

**Closed** 2016-10-31 15:14 UTC
Labels: status/duplicate
