### ISSUE TITLE
ConsoleInteraction: Typing Error in docstring

### ISSUE THREAD

**Issue by nikssardana** [coala/coala#2836] opened 2016-10-06 08:34 UTC
The first line of the docstring for print_affected_files contains a typing error

![screenshot from 2016-10-06 13-59-38](https://cloud.githubusercontent.com/assets/14257973/19145634/72669e88-8bcd-11e6-9e6c-e4bec4eba41e.png)
:

The line should contain the word "affected" instead of "afected".

**Comment by vreethesh** [comment] 2016-10-06 09:25
I would like to get assigned to this issue.

**Comment by deadpyxel** [comment] 2016-10-12 17:42
I'm kinda new on github, does only one person get assigned to each issue? or there can be a multiple number of pull requests related to the same issue? In advance, good project, and keep up the good work.

**Comment by Makman2** [comment] 2016-10-12 18:50
@deadpyxel yes only one shall work on a single issue to prevent doing the same work (as one PR needs to be abandoned in that case :/ ). This issue is already assigned, but feel free to take another one.
If you want to start with something a bit more challenging, you can also pick a `difficulty/low` issue :)

**Comment by deadpyxel** [comment] 2016-10-12 18:58
@Makman2 Much thanks, and sorry for screwing up that PR, I wasn't really sure what to do since I never did contribute to other peoples projects, and used Github mostly for my own college stuff. Thanks for the tip.

**Comment by Makman2** [comment] 2016-10-12 19:06
hehe no problem at all, it was your PR :D
PRs don't harm the repository as long as we don't merge them :)

**Comment by raul1991** [comment] 2016-10-13 09:29
Duplicate of issue #2808

**Comment by Makman2** [comment] 2016-10-13 09:36
oh indeed :+1: 
closing the other in favor of this issue as this one is being worked on.

**Closed** 2016-10-16 10:03 UTC
Labels: difficulty/newcomer, hacktoberfest
