### ISSUE TITLE
Newcomers_Guide.rst: fix link color in "Struggling with this? ..." message

### ISSUE THREAD

**Issue by nikitavbv** [coala/coala#5631] opened 2018-07-14 16:01 UTC
On Newcomers Guide page there is a block saying:

> Struggling with this? We have a very verbose guide on this topic in our Google Code In resources which can help you find a suitable repository and run coala on a bigger project.

where "our Google Code In resources" is a link. However, it is underlined with dark color (on dark background) making it unnoticeable for reader. Maybe it would be a good idea to change border color to a lighter one.

I attach the screenshot of this block to make things more clear:
![screenshot from 2018-07-14 18-57-07](https://user-images.githubusercontent.com/24596921/42726107-c07c2724-8797-11e8-8d90-c49314552f93.png)

**Comment by aditya81070** [comment] 2018-07-16 16:57
I would like to work on it.

**Comment by jayvdb** [comment] 2018-07-30 21:54
Duplicate of https://github.com/coala/coala/issues/4648

**Closed by jayvdb** 2018-07-30 21:54 UTC
Labels: area/documentation
