### ISSUE TITLE
Mistakes in Develepment_Setup.rst

### ISSUE THREAD

**Issue by jack17529** [coala/coala#3988] opened 2017-03-25 09:18 UTC
Newcomers is wrongly written replace by newcomer's.
Git is mentioned as Git instead of git.

**Comment by jack17529** [comment] 2017-03-25 09:19
Sending PR here - https://github.com/coala/coala/pull/3922

**Comment by jayvdb** [comment] 2017-03-25 09:23
Why do you mention #3922 here - that is an unrelated issue.

I am currently investigating this new issue, and will give it a difficulty rating shortly. If it is a newcomer issue, it should be left for someone else to solve it, so please do not send a PR yet.

**Comment by jayvdb** [comment] 2017-03-25 09:26
> Newcomers is wrongly written replace by newcomer's.

I can not find this problem in https://github.com/coala/coala/blob/2ac102/docs/Developers/Development_Setup.rst

> Git is mentioned as Git instead of git.

Ok, I see the section header "Installing from Git" , which could instead be "Installing from git" .

**Comment by jack17529** [comment] 2017-03-25 10:32
Oh its written like newcomers' , I have poor english ! , never saw something written like that before.

**Comment by jayvdb** [comment] 2017-03-25 10:53
The problem is it is half invalid ... wasting other peoples times.  As you say, you're English is not very good.  Do not try to raise bugs or fix grammatical issues.
The Git->git thing is not a problem.
Closing as invalid.

**Closed by jayvdb** 2017-03-25 10:53 UTC
Labels: difficulty/newcomer
