### ISSUE TITLE
Newcomers_Guide: Fix broken links

### ISSUE THREAD

**Issue by ashwini0529** [coala/coala#3239] opened 2016-12-13 22:32 UTC
- [ ] Fix `Git Basics` link under [this](https://github.com/coala/coala/blob/master/docs/Developers/Newcomers_Guide.rst#optional-get-help-with-git)
- [ ] Fix `Writing Good Commits` link under [this](https://github.com/coala/coala/blob/master/docs/Developers/Newcomers_Guide.rst#step-3-picking-up-an-issue)
- [ ] Fix `Review` link under [this](https://github.com/coala/coala/blob/master/docs/Developers/Newcomers_Guide.rst#step-7-waiting-for-review)

**Comment by adamki** [comment] 2016-12-14 06:13
i can take care of this. feel free to assign to me.

**Comment by Mariatta** [comment] 2016-12-14 06:23
@adamki Thanks for your interest :)
Please go through our newcomer guide at http://coala.io/newcomer and say Hello World at http://coala.io/chat

After that we can assign this issue to you.

**Comment by Mariatta** [comment] 2016-12-14 17:03
@ashwini0529 Can you be more specific of what kind of fix is needed here?

Thanks.

**Comment by ashwini0529** [comment] 2016-12-14 18:32
![selection_040](https://cloud.githubusercontent.com/assets/8419333/21195351/7147c03c-c259-11e6-855d-255c32c82b87.png)
![selection_041](https://cloud.githubusercontent.com/assets/8419333/21195420/b721fd34-c259-11e6-89ee-ab44bba46318.png)
![selection_042](https://cloud.githubusercontent.com/assets/8419333/21195435/c758c958-c259-11e6-965f-cdb6727e1ace.png)

All these needs to be corrected.

**Comment by Mariatta** [comment] 2016-12-14 18:40
This is a newcomer issue, and a newcomer may not understand what is wrong with the current link.
Please explain what the problem is, and how a newcomer can fix the link. For example by providing what the correct link is.
Hope this makes sense.
Thanks.

**Comment by adamki** [comment] 2016-12-14 22:07
just to confirm, the task includes fixing the broken links to the following destinations: 

https://github.com/coala/coala/blob/master/docs/Developers/Writing_Good_Commits.rst
https://github.com/coala/coala/blob/master/docs/Developers/Git_Basics.rst
https://github.com/coala/coala/blob/master/docs/Developers/Reviews.rst

thanks again!

**Comment by Nosferatul** [comment] 2016-12-14 22:40
Yes, go ahead!

**Comment by yash-nisar** [comment] 2016-12-15 08:57
Should we point the links to the docs ? @Nosferatul

**Comment by aptrishu** [comment] 2016-12-15 18:46
Point the links to docs. @adamki 
https://docs.coala/io

**Comment by ashwini0529** [comment] 2016-12-15 19:34
Please elaborate your commit message.

**Closed** 2016-12-22 00:57 UTC
Labels: difficulty/newcomer
